# Railway Monorepo Deployment Configuration
# Deploys both backend and frontend in a single Railway project

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20", "postgresql", "redis"]

[phases.install]
cmds = [
  "python3 -m pip install -r backend/requirements.txt",
  "cd frontend && npm ci --production=false"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/frontend_static",
  "cp -r frontend/build/* backend/frontend_static/"
]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"