# This nixpacks.toml is for monorepo deployment
# For Railway, we recommend deploying backend and frontend as separate services
# See RAILWAY_DEPLOYMENT.md for the recommended approach

[phases.setup]
nixPkgs = ["python311", "nodejs", "postgresql", "redis"]

[phases.install]
cmds = [
  "python3 -m pip install --user -r backend/requirements.txt",
  "cd frontend && npm ci --production=false"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"
